---

# Section 1: LAMP Script Execution on Slave Node (192.168.50.11)
- hosts: 192.168.50.11
  become: yes
  tasks:
    - name: Copy LAMP.sh script to slave node
      copy:
        src: /home/vagrant/Ansible/LAMP.sh
        dest: /home/vagrant/LAMP.sh
        mode: 0755

    - name: Execute LAMP.sh script on slave node
      shell: /home/vagrant/LAMP.sh

# Section 2: Cron Job for Uptime Monitoring on Slave Node (192.168.50.11)
- hosts: 192.168.50.11
  become: yes
  tasks:
    - name: Create the uptime script
      copy:
        content: |
          #!/bin/bash

          # Log the server's uptime to a file
          uptime > /var/log/uptime.log
        dest: /usr/local/bin/check_uptime.sh
        mode: '0755'

    - name: Create a cron job to check uptime every 12 am
      cron:
        name: Check uptime every 12 am
        job: "/usr/local/bin/check_uptime.sh"
        minute: '0'
        hour: '0'
        state: present

    - name: Display uptime log file
      shell: cat /var/log/uptime.log
      register: uptime_output

    - name: Display the server's uptime
      debug:
        msg: "{{ uptime_output.stdout }}"

# Section 3: Fetching PHP Application Content on Slave Node (192.168.50.11)
- hosts: 192.168.50.11
  become: yes
  tasks:
    - name: Fetch PHP application content using curl
      command: "curl -s http://192.168.50.11"  # Silent HTTP GET request
      register: php_application
      ignore_errors: true

    - name: Display content of PHP application
      debug:
        msg: "PHP Application Content:\n{{ php_application.stdout }}"

